apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: juphc-tc_pipeline
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  params:
    - name: IMAGE_URL
      value: "docker.io/username/tax-calculator:latest"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi